development/config/routes.rb
Rails.application.routes.draw do

  # Only for ENV=development
  # mount Logster::Web => "/logs"

  resources :providers do
    collection do
      get :schedule
      get :add_patient
      get :show_myaccount
      get :request_emergency_access
      patch :update_emergency_access
      get :set_emergency_access
      get :set_status
      get :invite_to_portal
      get :download_pdf
      get :send_invite_email
      get :add_patient_from_appointment
      post :save_message
      get :destroy_message
      get :prev_message
      get :next_message
      get :first_message
      get :patients
      get :lock
      post :unlock
    end
  end

  resources :patients,     only: [:index, :create, :update] do
    collection do
      post :simple_create
      get  :appointments_show
      get  :appointments_status_actions
      get  :new_appointment
      get  :provider_full_info
      get  :myprofile
      patch :update_myprofile
      get  :myhealth
      post :create_emergency_contact
    end
  end

  resources :appointments, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get :referrals
      get :patients
      get :patient_full_info
      get :reschedule
    end
  end

  resources :block_outs, only: [:create]

  resources :referrals,  only: [:new, :create]

  resources :patient_appointments, only: [:create]

  resources :practices, only: [:new, :create, :edit, :update]

  resources :locations, only: [:create, :update] do
    collection do
      get :form
      get :primary_location
    end
  end

  resources :immunizations, except: [:destroy, :show] do
    collection do
      get  :name_block
      post :vaccines
    end
  end

  namespace :settings do
    get   :practice
    get   :access_permissions
    patch :update_permissions
    get   :set_admin
    get   :schedule
    patch :update_schedule
    get   :add_user_added_practice
    get   :set_practice_location_color
    get   :get_schedule_fields
    get   :update_schedule_fields
    get   :update_schedule_color_fields
    get   :add_schedule_fields
    get   :destroy_schedule_fields
  end

  resources :patient_treatments, only: [:index] do
    collection do
      get  :search_patients
      get  :active_patients
      get  :show_patient_main
      get  :tooth_activity
      get  :show_patient_diagnoses
      get  :diagnosis_codes
      get  :show_patient_medications
      get  :add_patient_diagnoses
      post :create_diagnosis
      patch :update_diagnosis
      get  :add_patient_medications
      post :create_medication
      patch :update_medication
      get  :portions
      get  :medications
      get  :show_patient_allergy
      post :create_allergy
      patch :update_allergy
      get  :edit_patient_smoking
      post :update_smoking_status
      get  :add_patient_medical_history
      patch :update_medical_history
      get  :add_patient_advanced_directives
      patch :update_advanced_directive
      get  :add_patient_insurance
      get  :add_patient_payer
      get  :show_patient_full_perio
      patch :update_full_perio
      get  :show_patient_perio_data_entry
      patch :update_tooth
      get  :set_tooth_bsp
      get  :add_patient_encounter
      post :create_patient_encounter
      patch :update_encounter
      get  :providers
      get  :procedures
      get  :procedure_codes
      get  :encounters
      get  :add_patient_procedure
      get  :show_patient_procedure
      post :create_procedure
      patch :update_procedure
      get  :encounter_full_info
      patch :update_guarantor
      post :create_payer
      post :create_insurance
      get :payers
      get :guarantor
    end
  end

  resources :representatives do
    collection do
      post :activate
    end
    member do
      post :reset_password
    end
  end

  resources :email_messages, only: [:index, :new, :create] do
    collection do
      get  :add_subject
      get :get_subjects
      get :update_subject
      get :remove_subject
      post :create_main
      post :create_to_practice
      post :create_from_patient_to_practice
      post :create_reply
      get  :patients
      get  :practices
      get  :patient_practices
      get :open_message
      get :new_message_to_patient
      get :forward_message_from_patient
      get :new_message_in_practice
      get :new_message_to_practice
      get :reply_to_message_in_practice_contacts
      get :forward_message_in_practice_contacts
      get :contacts
      get :contacts_pagination
      get :contacts_practices
      get :find_practices
      get :add_contact
      get :new_contact
      get :message
      get :new_tab
      get :to_archive
      get :delete_message
      get :search_message
      get :favorite_contact
      get :mark_as_read
    end
  end

  get 'landings/index'
  get 'admin/index'

  post 'text', to: 'text_messages#create'

  root to: 'landings#index'

  devise_for :users,
    path_names: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-two-factor',
      verify_authy_installation: '/verify-installation'
    },
    controllers: {
      confirmations: 'confirmations',
      passwords:     'passwords',
      registrations: 'registration',
      sessions:      'sessions',
      devise_authy:  'authy'
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :calendars do
    collection do
      get :schedule
      get :open_reschedule
      patch :reschedule
      get :get_calendars
      get :filter
      get :new_appointment
      get :targets
    end
    member do
      post :move
      post :resize
    end
  end

  resources :tables, except: [:show] do
    collection do
      get :records
    end
  end

  namespace :sorter do
    get :appointments
    get :messages
    get :todos
  end

  namespace :dashboard do
    get :index
  end

  namespace :practice_sessions do
    get :sign_in
  end

  namespace :zipcode do
    post :city_set
    post :state_set
    post :zip_set
  end

  namespace :web_console do
    get :show_web_console_alert
  end

  match 'admin',    to: 'admin#index',  via: [:get]
  match 'explorer', to: 'tables#index', via: [:get]

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

development/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # before_filter :check_role
  before_filter :prepare_model_name, only:   [:records]
  before_filter :set_class_name,     except: [:index]
  before_filter :set_fields_and_associations, only: [:new, :edit]
  before_filter :find_instance,      only:   [:edit, :update, :destroy]

  layout 'tables'

  def index
    @models = Dir.glob("#{Rails.root}/app/models/*.rb").map{ |path| File.basename(path).gsub('.rb', '').gsub('_', ' ').capitalize }.sort
  end

  def records
    @models = Dir.glob("#{Rails.root}/app/models/*.rb").map{ |path| File.basename(path).gsub('.rb', '').gsub('_', ' ').capitalize }.sort
    @records      = @class_name.all.page(params[:page]).per(50)
    @fields       = @class_name.fields.reject{ |field| field.to_s.include? '_id' }
    @associations = ClassBuilder.associations(@class_name)
  end

  def new
  end

  def create
    instance = @class_name.create(class_params)
    if instance.persisted?
      flash[:notice] = "#{@class_name} created successfully"
      redirect_to records_tables_path(model_name: params[:model_name])
    else
      flash[:error] = instance.errors.full_messages.to_sentence
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @instance.update(class_params)
      flash[:notice] = "#{@class_name} updated successfully"
      redirect_to records_tables_path(model_name: params[:model_name])
    else
      flash[:error] = @instance.errors.full_messages.to_sentence
      redirect_to :back
    end
  end

  def destroy
    @instance.destroy
    flash[:notice] = "#{@class_name} deleted successfully"
    redirect_to records_tables_path(model_name: params[:model_name])
  end

  protected

  def prepare_model_name
    params[:model_name] = params[:model_name].gsub(' ', '_').camelcase
  end

  def set_class_name
    @class_name = params[:model_name].constantize
  end

  def set_fields_and_associations
    @fields       = changable_fields
    @associations = ClassBuilder.associations(@class_name)
  end

  def find_instance
    @instance = @class_name.find(params[:id])
  end

  def class_params
    class_name_sym = params[:model_name].downcase.to_sym

    fields = changable_fields
    fields.each do |field, configs|
      # convert string to time
      params[class_name_sym][field] = params[class_name_sym][field].to_time if configs[:type] == Time
      # convert string to integer
      params[class_name_sym][field] = params[class_name_sym][field].to_i    if configs[:type] == Integer
    end

    # posibility to set nil association
    associations = ClassBuilder.associations(@class_name)
    associations.each do |class_name, target_name|
      params[class_name_sym]["#{target_name}_id"] = nil if params[class_name_sym]["#{target_name}_id"].blank?
    end

    params.require(class_name_sym).permit(fields.keys + association_params)
  end

  def changable_fields
    ClassBuilder.fields(@class_name)
  end

  def association_params
    ClassBuilder.associations(@class_name).map{ |a| "#{a[1].to_s}_id" }
  end

  def check_role
    authorize :admin, :admin?
  end
end

development/app/helpers/tables_helper.rb
module TablesHelper
  def input(f, field, field_type, class_name)
    case field_type.to_s
      when 'String'
        f.input field.to_sym, input_html: { class: 'form-control', placeholder: field }
      when 'Integer'
        f.input field.to_sym, input_html: { class: 'form-control', placeholder: field }
      when 'Float'
        f.input field.to_sym, input_html: { class: 'form-control', placeholder: field }
      when 'Text'
        f.input field.to_sym, as: :text, input_html: { class: 'form-control', placeholder: field }
      when 'Time'
        f.input field.to_sym, input_html: { class: 'form-control', placeholder: field }
      when 'Enum'
        f.input field.to_sym, as: :select, collection: class_name.send(field.to_s.pluralize).to_a, input_html: { 'data-placeholder': field, 'data-theme': 'gray-lighter', 'data-arrow': '2x', 'data-padding': '3x', 'data-font': '1x', class: 'select2' }
      when 'Boolean'
        "<div class=checkbox-custom>
          #{f.check_box field.to_sym, label: false, id: field.to_sym}
          <label for=#{field.to_sym}>
            <span class=checkbox-icon-container>
              <span class=checkbox-icon></span>
            </span>
            <span class=checkbox-label>
              #{field.to_s.titleize}
            </span>
          </label>
        </div>".html_safe
    end
  end
end

development/app/views/tables/_form.slim
= hidden_field_tag :model_name, class_name.to_s
- fields.each do |field, configs|
  .row
    .col-lg-12
      .form-group
        = input(f, field, configs[:type], class_name)
- associations.each do |class_name, target_name|
  .row
    .col-lg-12
      .form-group
        = f.input "#{target_name.to_s}_id", as: :select, collection: class_name.constantize.all.to_a, input_html: { 'data-placeholder': class_name, 'data-theme': 'gray-lighter', 'data-arrow': '2x', 'data-padding': '3x', 'data-font': '1x', class: 'select2' }

development/app/views/tables/_form_edit.slim
.modal-dialog
  .modal-content
    .modal-header
      p.title 
        = "Edit #{@class_name}" 
      a.close-button href="#" data-dismiss="modal"
    = simple_form_for @instance, url: table_path(@instance) do |f|
      .modal-body
        .scrollable-container
          .content
            = render 'form', f: f, class_name: @class_name, fields: @fields, associations: @associations
      .modal-footer
        .controls
          = f.button :submit, 'Save', class: 'button'
          a.button href="#" data-dismiss="modal" Cancel

development/app/views/tables/_form_new.slim
.modal-dialog
  .modal-content
    .modal-header
      p.title 
        = "Add #{@class_name}" 
      a.close-button href="#" data-dismiss="modal"
    = simple_form_for @class_name.new, url: tables_path do |f|
      .modal-body
        .scrollable-container
          .content
            = render 'form', f: f, class_name: @class_name, fields: @fields, associations: @associations
      .modal-footer
        .controls
          = f.button :submit, 'Add', class: 'button'
          a.button href="#" data-dismiss="modal" Cancel

development/app/views/tables/edit.js.erb
$('#modal-tables-edit-record').html("<%= escape_javascript(render 'form_edit') %>");

initPickers();
initModalsReposition();
initSelect2('#modal-tables-edit-record');

if(!$('#modal-tables-edit-record').hasClass('in'))
  $('#modal-tables-edit-record').modal("show");

development/app/views/tables/index.slim
.container-fluid.tables-container.tables-index-container
  .row
    .col-lg-3.col-md-3.col-sm-3.left-block
      .panel.panel-default
        .panel-heading
          | Tables List
        .panel-body
          ul
            - @models.each do |model_name|
              li
                = link_to model_name, records_tables_path(model_name: model_name)
        .panel-footer
          = "Tables Count: #{@models.size}"
    .col-lg-9.col-md-9.col-sm-9.right-block

development/app/views/tables/new.js.erb
$('#modal-tables-new-record').html("<%= escape_javascript(render 'form_new') %>");

initPickers();
initModalsReposition();
initSelect2('#modal-tables-new-record');

if(!$('#modal-tables-new-record').hasClass('in'))
  $('#modal-tables-new-record').modal("show");

development/app/views/tables/records.slim
.container-fluid.tables-container.tables-records-container
  .row
    .col-lg-3.col-md-3.col-sm-3.left-block
      .panel.panel-default
        .panel-heading
          | Tables List
        .panel-body
          ul
            - @models.each do |model_name|
              li
                = link_to model_name, records_tables_path(model_name: model_name)
        .panel-footer
          = "Tables Count: #{@models.length}"
    .col-lg-9.col-md-9.col-sm-9.right-block
      .panel
        .panel-heading
          .row
            .col-lg-8.col-md-8.col-sm-8.col-xs-6
              p.title
                = @class_name.to_s
            .col-lg-4.col-md-4.col-sm-4.col-xs-6
              .controls
                = link_to "Add", new_table_path(model_name: @class_name.to_s), class: 'button button-success button-new', remote: true
        .panel-body
          .table-responsive
            table.table
              thead
                tr
                  - @fields.each do |field, _|
                    th
                      = field
                  - @associations.each do |class_name, target_name|
                    th
                      = class_name
                  th
                  th
              tbody
                - if @records.any?
                  - @records.each do |record|
                    tr
                      - @fields.each do |field, _|
                        td
                          = record.send(field)
                      - @associations.each do |class_name, target_name|
                        td
                          = link_to record.send(target_name).to_s, records_tables_path(model_name: class_name.underscore.humanize)
                      td
                        = link_to 'Edit', edit_table_path(record, model_name: @class_name.to_s), class: 'button button-info', remote: true
                      td
                        = link_to 'Delete', table_path(record, model_name: @class_name.to_s), method: :delete, class: 'button button-danger'
                - else
                  tr.message
                    td colspan="#{@fields.size + @associations.size + 2}"
                      | Records don't found. Please add new.
          = will_paginate @records, renderer: BootstrapPagination::Rails, previous_label: I18n.t('previous_label'), next_label: I18n.t('next_label')
#modal-tables-new-record.modal-tables.modal.fade
#modal-tables-edit-record.modal-tables.modal.fade