development/config/routes.rb
Rails.application.routes.draw do

  # Only for ENV=development
  # mount Logster::Web => "/logs"

  resources :providers do
    collection do
      get :schedule
      get :add_patient
      get :show_myaccount
      get :request_emergency_access
      patch :update_emergency_access
      get :set_emergency_access
      get :set_status
      get :invite_to_portal
      get :download_pdf
      get :send_invite_email
      get :add_patient_from_appointment
      post :save_message
      get :destroy_message
      get :prev_message
      get :next_message
      get :first_message
      get :patients
      get :lock
      post :unlock
    end
  end

  resources :patients,     only: [:index, :create, :update] do
    collection do
      post :simple_create
      get  :appointments_show
      get  :appointments_status_actions
      get  :new_appointment
      get  :provider_full_info
      get  :myprofile
      patch :update_myprofile
      get  :myhealth
      post :create_emergency_contact
    end
  end

  resources :appointments, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get :referrals
      get :patients
      get :patient_full_info
      get :reschedule
    end
  end

  resources :block_outs, only: [:create]

  resources :referrals,  only: [:new, :create]

  resources :patient_appointments, only: [:create]

  resources :practices, only: [:new, :create, :edit, :update]

  resources :locations, only: [:create, :update] do
    collection do
      get :form
      get :primary_location
    end
  end

  resources :immunizations, except: [:destroy, :show] do
    collection do
      get  :name_block
      post :vaccines
    end
  end

  namespace :settings do
    get   :practice
    get   :access_permissions
    patch :update_permissions
    get   :set_admin
    get   :schedule
    patch :update_schedule
    get   :add_user_added_practice
    get   :set_practice_location_color
    get   :get_schedule_fields
    get   :update_schedule_fields
    get   :update_schedule_color_fields
    get   :add_schedule_fields
    get   :destroy_schedule_fields
  end

  resources :patient_treatments, only: [:index] do
    collection do
      get  :search_patients
      get  :active_patients
      get  :show_patient_main
      get  :tooth_activity
      get  :show_patient_diagnoses
      get  :diagnosis_codes
      get  :show_patient_medications
      get  :add_patient_diagnoses
      post :create_diagnosis
      patch :update_diagnosis
      get  :add_patient_medications
      post :create_medication
      patch :update_medication
      get  :portions
      get  :medications
      get  :show_patient_allergy
      post :create_allergy
      patch :update_allergy
      get  :edit_patient_smoking
      post :update_smoking_status
      get  :add_patient_medical_history
      patch :update_medical_history
      get  :add_patient_advanced_directives
      patch :update_advanced_directive
      get  :add_patient_insurance
      get  :add_patient_payer
      get  :show_patient_full_perio
      patch :update_full_perio
      get  :show_patient_perio_data_entry
      patch :update_tooth
      get  :set_tooth_bsp
      get  :add_patient_encounter
      post :create_patient_encounter
      patch :update_encounter
      get  :providers
      get  :procedures
      get  :procedure_codes
      get  :encounters
      get  :add_patient_procedure
      get  :show_patient_procedure
      post :create_procedure
      patch :update_procedure
      get  :encounter_full_info
      patch :update_guarantor
      post :create_payer
      post :create_insurance
      get :payers
      get :guarantor
    end
  end

  resources :representatives do
    collection do
      post :activate
    end
    member do
      post :reset_password
    end
  end

  resources :email_messages, only: [:index, :new, :create] do
    collection do
      get  :add_subject
      get :get_subjects
      get :update_subject
      get :remove_subject
      post :create_main
      post :create_to_practice
      post :create_from_patient_to_practice
      post :create_reply
      get  :patients
      get  :practices
      get  :patient_practices
      get :open_message
      get :new_message_to_patient
      get :forward_message_from_patient
      get :new_message_in_practice
      get :new_message_to_practice
      get :reply_to_message_in_practice_contacts
      get :forward_message_in_practice_contacts
      get :contacts
      get :contacts_pagination
      get :contacts_practices
      get :find_practices
      get :add_contact
      get :new_contact
      get :message
      get :new_tab
      get :to_archive
      get :delete_message
      get :search_message
      get :favorite_contact
      get :mark_as_read
    end
  end

  get 'landings/index'
  get 'admin/index'

  post 'text', to: 'text_messages#create'

  root to: 'landings#index'

  devise_for :users,
    path_names: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-two-factor',
      verify_authy_installation: '/verify-installation'
    },
    controllers: {
      confirmations: 'confirmations',
      passwords:     'passwords',
      registrations: 'registration',
      sessions:      'sessions',
      devise_authy:  'authy'
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :calendars do
    collection do
      get :schedule
      get :open_reschedule
      patch :reschedule
      get :get_calendars
      get :filter
      get :new_appointment
      get :targets
    end
    member do
      post :move
      post :resize
    end
  end

  resources :tables, except: [:show] do
    collection do
      get :records
    end
  end

  namespace :sorter do
    get :appointments
    get :messages
    get :todos
  end

  namespace :dashboard do
    get :index
  end

  namespace :practice_sessions do
    get :sign_in
  end

  namespace :zipcode do
    post :city_set
    post :state_set
    post :zip_set
  end

  namespace :web_console do
    get :show_web_console_alert
  end

  match 'admin',    to: 'admin#index',  via: [:get]
  match 'explorer', to: 'tables#index', via: [:get]

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

development/app/models/representative.rb
class Representative
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  field :first_name,       type: String
  field :last_name,        type: String
  field :primary_phone,    type: String
  field :active,           type: Boolean,    default: false

  belongs_to :patient
  belongs_to :user
end

development/app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  before_filter :check_role
  before_filter :find_patient
  before_filter :prepare_user_params,      only: [:create]
  before_filter :find_representative,      only: [:edit, :update, :show, :destroy, :activate, :reset_password]
  before_filter :find_all_representatives, only: [:index, :activate]

  def index
  end

  def new
    @user = User.new
    @representative = Representative.new
  end

  def create
    if params[:representative_policy]
      user = User.create(user_params)
      if user.persisted?
        representative = Representative.create(representative_params.merge({ user_id: user.id, patient_id: @patient.id }))
        if representative.persisted?
          InvitationMailer.send_representative_invitation(user.email, representative.first_name, @patient.full_name, @code).deliver_now
          flash[:notice] = 'Representative created successfully'
          redirect_to representatives_path(patient_id: @patient.id)
        else
          flash[:error] = representative.errors.full_messages.to_sentence
          redirect_to :back
        end
      else
        flash[:error] = user.errors.full_messages.to_sentence
        redirect_to :back
      end
    else
      flash[:error] = 'You should agree with representative policy'
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      if @representative.update(representative_params)
        flash[:notice] = 'Representative updated successfully'
        redirect_to representatives_path(patient_id: @patient.id)
      else
        flash[:error] = @representative.errors.full_messages.to_sentence
        redirect_to :back
      end
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      redirect_to :back
    end
  end

  def show
  end

  def destroy
    @representative.destroy
    render nothing: true
  end

  def activate
    @representatives.update_all(active: false) if @representatives.where(active: true).any?
    @representative.update(active: params[:active])
    render nothing: true
  end

  def reset_password
    code = Activation.code
    @user.update(password: code, password_confirmation: code)
    InvitationMailer.send_representative_reset_password(@user.email, @representative.first_name, @patient.full_name, code).deliver_now
  end

  protected

  def find_patient
    @patient = current_user.provider.all_patients.find(params[:patient_id])
  end

  def prepare_user_params
    @code = Activation.code
    params[:representative][:user].merge!({ password: @code,
                                            password_confirmation: @code,
                                            confirmed_at: Time.now,
                                            role: :Representative })
  end

  def find_representative
    @representative = @patient.representatives.find(params[:id])
    @user = @representative.user
  end

  def find_all_representatives
    @representatives = @patient.representatives
  end

  def user_params
    params.require(:representative).require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :role
    )
  end

  def representative_params
    params.require(:representative).permit(
        :patient_id,
        :first_name,
        :last_name,
        :primary_phone
    )
  end

  def check_role
    authorize Patient, :update?
  end
end

development/app/views/representatives/_form.html.slim
.modal-dialog.modal-md
  = flash[:error]
  = simple_form_for @representative, remote: true, html: { class: 'modal-content' } do |f|
    = hidden_field_tag :patient_id, @patient.id
    .modal-header
      p.title
        = "#{ type } Authorized Representative"
      a.close-button href="#" data-dismiss="modal"
    .modal-body
      .scrollable-container
        .content
          .row
            .col-lg-12
              .form-group
                = f.input :first_name, input_html: { class: 'form-control', placeholder: 'First Name' }
          .row
            .col-lg-12
              .form-group
                = f.input :last_name, input_html: { class: 'form-control', placeholder: 'Last Name' }
          .row
            .col-lg-12
              .form-group
                = f.simple_fields_for @user do |u|
                  = u.input :email, as: :email, input_html: { class: 'form-control', placeholder: 'Email' }
          .row
            .col-lg-12
              .form-group
                = f.input :primary_phone, input_html: { class: 'form-control input-phone', placeholder: 'Primary Contact Phone' }
          - if type == 'Add'
            .row
              .col-lg-12
                .form-group
                  .checkbox-custom
                    = check_box_tag :representative_policy, false, class: 'checkbox'
                    label for="representative_policy"
                      span.checkbox-icon-container
                        span.checkbox-icon
                      span.checkbox-label
                        | Representative has read and signed  
                        a href="#" Authorized Representative Acceptable Use Policy
    .modal-footer
      .controls
        - if type != 'View'
          = f.submit 'Save', class: 'button'
        a.button href="#" data-dismiss="modal" Close

development/app/views/representatives/_index_form.html.slim
.modal-dialog.modal-lg
  .modal-content
    .modal-header
      p.title
        = "Authorized Representative#{ 's' if @representatives.count > 1 }"
      a.close-button href="#" data-dismiss="modal"
    .modal-body
      .scrollable-container
        .content
          .row
            .col-lg-12
              .table-responsive
                table.table#representative-table
                  thead
                    tr
                      th
                        | Full Name
                      th
                        | Primary Email
                      th
                        | Contact Phone
                      th
                        | Active
                      th
                        | Actions
                  - if @representatives.any?
                    tbody
                      - @representatives.each do |representative|
                        tr
                          td
                            = link_to "#{representative.last_name}, #{representative.first_name}", '#'
                          td
                            = representative.user.email
                          td
                            = representative.primary_phone
                          td
                            .checkbox-custom
                              = check_box_tag :active, nil, representative.active, { id: representative.id }
                              label for="#{representative.id}"
                                span.checkbox-icon-container
                                  span.checkbox-icon
                          td.controls
                            = link_to 'View', representative_path(representative, patient_id: @patient.id), remote: true, class: 'button button-modal-open', 'data-target' => '#modal-patient-show-authorized-representative'
                            = link_to 'Edit', edit_representative_path(representative, patient_id: @patient.id), remote: true, class: 'button button-modal-open', 'data-target' => '#modal-patient-edit-authorized-representative'
                            = link_to 'Reset Password', reset_password_representative_path(representative, patient_id: @patient.id), remote: true, method: :post, class: 'button button-modal-open', 'data-target' => '#modal-patient-reset-password-authorized-representative'
                            = link_to 'Delete', representative_path(representative, patient_id: @patient.id), remote: true, method: :delete, class: 'button button-danger destroy-button', id: representative.id
                  - else
                    tbody
                      tr
                        td.message colspan="5"
                          | No Representatives Found
    .modal-footer
      .controls
        = link_to 'Add New', new_representative_path(patient_id: @patient.id), remote: true, class: 'button button-modal-open', 'data-target' => '#modal-patient-add-authorized-representative'

development/app/views/representatives/_reset_password_form.html.slim
.modal-dialog.modal-md
  .modal-content
    .modal-header
      p.title Reset Password
      a.close-button href="#" data-dismiss="modal"
    .modal-body
      .scrollable-container
        .content
          .row
            .col-lg-12
              .form-group
                p.message Password Reset email has been sent to Authorized Representatives Primary Email on Record.
    .modal-footer

development/app/views/representatives/edit.js.erb
$("#modal-patient-edit-authorized-representative").html("<%= escape_javascript(render 'form', type: 'Edit') %>")
$("#modal-patient-edit-authorized-representative").modal("show")

initPickers('#modal-patient-edit-authorized-representative');
initSelect2('#modal-patient-edit-authorized-representative');

development/app/views/representatives/index.js.erb
$("#modal-patient-all-authorized-representatives").html("<%= escape_javascript(render 'index_form') %>")
$("#modal-patient-all-authorized-representatives").modal("show")

initPickers('#modal-patient-all-authorized-representatives');
initSelect2('#modal-patient-all-authorized-representatives');
initModalFadeInOut('#modal-patient-all-authorized-representatives');
$("#modal-patient-add-authorized-representative").modal("hide");
$("#modal-patient-edit-authorized-representative").modal("hide");

$('#representative-table .checkbox-custom input').click(function() {
  var this_check_box = $(this);
  $.ajax({
    type: 'POST',
    url: '<%= activate_representatives_path %>',
    data: {
      patient_id: '<%= @patient.id %>',
      id: this_check_box.attr('id'),
      active: this_check_box.is(':checked')
    }
  }).done(function() {
    if(this_check_box.is(':checked')) {
      $('#representative-table .checkbox-custom input').prop('checked', false);
      this_check_box.prop('checked', true);
    }
  });
});

$('#representative-table .destroy-button').click(function() {
  $(this).closest('tr').remove();
  if($('#representative-table tbody tr').length == 0) {
    $('#representative-table tbody').remove();
    $('#representative-table').append('<tbody><tr><td class="message" colspan="5">No Representatives Found</td></tr><tbody>');
  }
});

development/app/views/representatives/new.js.erb
$("#modal-patient-add-authorized-representative").html("<%= escape_javascript(render 'form', type: 'Add' ) %>")
$("#modal-patient-add-authorized-representative").modal("show")

initPickers('#modal-patient-add-authorized-representative');
initSelect2('#modal-patient-add-authorized-representative');

development/app/views/representatives/reset_password.js.erb
$("#modal-patient-reset-password-authorized-representative").html("<%= escape_javascript(render 'reset_password_form') %>")
$("#modal-patient-reset-password-authorized-representative").modal("show")

initPickers('#modal-patient-reset-password-authorized-representative');
initSelect2('#modal-patient-reset-password-authorized-representative');

development/app/views/representatives/show.js.erb
$("#modal-patient-show-authorized-representative").html("<%= escape_javascript(render 'form', type: 'View') %>")
$("#modal-patient-show-authorized-representative").modal("show")

initPickers('#modal-patient-show-authorized-representative');
initSelect2('#modal-patient-show-authorized-representative');

$('#modal-patient-show-authorized-representative input').attr('disabled', true);