development/config/routes.rb
Rails.application.routes.draw do

  # Only for ENV=development
  # mount Logster::Web => "/logs"

  resources :providers do
    collection do
      get :schedule
      get :add_patient
      get :show_myaccount
      get :request_emergency_access
      patch :update_emergency_access
      get :set_emergency_access
      get :set_status
      get :invite_to_portal
      get :download_pdf
      get :send_invite_email
      get :add_patient_from_appointment
      post :save_message
      get :destroy_message
      get :prev_message
      get :next_message
      get :first_message
      get :patients
      get :lock
      post :unlock
    end
  end

  resources :patients,     only: [:index, :create, :update] do
    collection do
      post :simple_create
      get  :appointments_show
      get  :appointments_status_actions
      get  :new_appointment
      get  :provider_full_info
      get  :myprofile
      patch :update_myprofile
      get  :myhealth
      post :create_emergency_contact
    end
  end

  resources :appointments, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get :referrals
      get :patients
      get :patient_full_info
      get :reschedule
    end
  end

  resources :block_outs, only: [:create]

  resources :referrals,  only: [:new, :create]

  resources :patient_appointments, only: [:create]

  resources :practices, only: [:new, :create, :edit, :update]

  resources :locations, only: [:create, :update] do
    collection do
      get :form
      get :primary_location
    end
  end

  resources :immunizations, except: [:destroy, :show] do
    collection do
      get  :name_block
      post :vaccines
    end
  end

  namespace :settings do
    get   :practice
    get   :access_permissions
    patch :update_permissions
    get   :set_admin
    get   :schedule
    patch :update_schedule
    get   :add_user_added_practice
    get   :set_practice_location_color
    get   :get_schedule_fields
    get   :update_schedule_fields
    get   :update_schedule_color_fields
    get   :add_schedule_fields
    get   :destroy_schedule_fields
  end

  resources :patient_treatments, only: [:index] do
    collection do
      get  :search_patients
      get  :active_patients
      get  :show_patient_main
      get  :tooth_activity
      get  :show_patient_diagnoses
      get  :diagnosis_codes
      get  :show_patient_medications
      get  :add_patient_diagnoses
      post :create_diagnosis
      patch :update_diagnosis
      get  :add_patient_medications
      post :create_medication
      patch :update_medication
      get  :portions
      get  :medications
      get  :show_patient_allergy
      post :create_allergy
      patch :update_allergy
      get  :edit_patient_smoking
      post :update_smoking_status
      get  :add_patient_medical_history
      patch :update_medical_history
      get  :add_patient_advanced_directives
      patch :update_advanced_directive
      get  :add_patient_insurance
      get  :add_patient_payer
      get  :show_patient_full_perio
      patch :update_full_perio
      get  :show_patient_perio_data_entry
      patch :update_tooth
      get  :set_tooth_bsp
      get  :add_patient_encounter
      post :create_patient_encounter
      patch :update_encounter
      get  :providers
      get  :procedures
      get  :procedure_codes
      get  :encounters
      get  :add_patient_procedure
      get  :show_patient_procedure
      post :create_procedure
      patch :update_procedure
      get  :encounter_full_info
      patch :update_guarantor
      post :create_payer
      post :create_insurance
      get :payers
      get :guarantor
    end
  end

  resources :representatives do
    collection do
      post :activate
    end
    member do
      post :reset_password
    end
  end

  resources :email_messages, only: [:index, :new, :create] do
    collection do
      get  :add_subject
      get :get_subjects
      get :update_subject
      get :remove_subject
      post :create_main
      post :create_to_practice
      post :create_from_patient_to_practice
      post :create_reply
      get  :patients
      get  :practices
      get  :patient_practices
      get :open_message
      get :new_message_to_patient
      get :forward_message_from_patient
      get :new_message_in_practice
      get :new_message_to_practice
      get :reply_to_message_in_practice_contacts
      get :forward_message_in_practice_contacts
      get :contacts
      get :contacts_pagination
      get :contacts_practices
      get :find_practices
      get :add_contact
      get :new_contact
      get :message
      get :new_tab
      get :to_archive
      get :delete_message
      get :search_message
      get :favorite_contact
      get :mark_as_read
    end
  end

  get 'landings/index'
  get 'admin/index'

  post 'text', to: 'text_messages#create'

  root to: 'landings#index'

  devise_for :users,
    path_names: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-two-factor',
      verify_authy_installation: '/verify-installation'
    },
    controllers: {
      confirmations: 'confirmations',
      passwords:     'passwords',
      registrations: 'registration',
      sessions:      'sessions',
      devise_authy:  'authy'
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :calendars do
    collection do
      get :schedule
      get :open_reschedule
      patch :reschedule
      get :get_calendars
      get :filter
      get :new_appointment
      get :targets
    end
    member do
      post :move
      post :resize
    end
  end

  resources :tables, except: [:show] do
    collection do
      get :records
    end
  end

  namespace :sorter do
    get :appointments
    get :messages
    get :todos
  end

  namespace :dashboard do
    get :index
  end

  namespace :practice_sessions do
    get :sign_in
  end

  namespace :zipcode do
    post :city_set
    post :state_set
    post :zip_set
  end

  namespace :web_console do
    get :show_web_console_alert
  end

  match 'admin',    to: 'admin#index',  via: [:get]
  match 'explorer', to: 'tables#index', via: [:get]

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

development/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_filter :check_role
  before_action :set_provider, only: [:show, :edit, :destroy]
  before_action :check_lock, except: [:index, :unlock]
  before_action :find_message, only: [:open_message, :reply_message, :destroy_message,
                                      :prev_message, :next_message]
  skip_before_filter :verify_authenticity_token, only: [:save_message]

  layout 'provider'

  before_filter :prepare_params, only: [:update]

  def index
    authorize Provider, :provider?
    @appointments = current_user.provider.appointments.page(params[:page]).per(10)
    @messages = current_user.inbox
    @to_dos   = @appointments.map(&:to_do)
  end

  def show
    authorize Provider, :provider?
    @provider = current_user.providers.find(params[:id])
  end

  def new
    authorize Provider, :provider?
    @provider = current_user.provider.new
  end

  def add_patient
    authorize Patient, :create?
    @user = User.new
  end

  def download_pdf
    authorize Patient, :create?
    pdf = InvitationPdf.new(params[:name], params[:birth], params[:code])
    send_data pdf.render,
              filename: 'PatientPortal-Invitation.pdf',
              type: 'application/pdf'
  end

  def send_invite_email
    authorize Patient, :create?
    InvitationMailer.send_invitation(params[:name], params[:last_name], params[:birth], params[:code], params[:email]).deliver
    render nothing: true
  end

  def add_patient_from_appointment
    authorize Patient, :create?
    @user = User.new
  end

  def show_myaccount
    authorize Provider, :provider?
  end

  def request_emergency_access
    authorize Provider, :provider?
  end

  def update_emergency_access
    authorize Provider, :provider?
    provider = current_user.provider
    if provider.update(emergency_access_reason: params[:provider][:emergency_access_reason], emergency_access: true)
      flash[:notice] = 'Emergency access was sent successfully'
    else
      flash[:error] = provider.errors.full_messages.to_sentence
    end
    redirect_to :back
  end

  def set_emergency_access
    params[:emergency_access] ? authorize(Provider, :admin?) : authorize(Provider, :provider?)
    Provider.find(params[:id]).update(emergency_access: params[:emergency_access])
    redirect_to :back
  end

  def set_status
    authorize Provider, :admin?
    Provider.find(params[:id]).update(status: params[:status])
    redirect_to :back
  end

  def invite_to_portal
    authorize Patient, :create?
    @patient = Patient.find(params[:patient_id])
  end

  def save_message
    authorize EmailMessage, :show?
    message = EmailMessage.create(message_params.merge({to_id: params[:email_message][:to_id], from_id: current_user.id}))
    if message.persisted?
      EmailMessagesMailer.send_message(message).deliver if params[:commit] == 'Send'
      flash[:notice] = 'Message saved successfully'
      remote_redirect_to providers_path
    else
      flash[:error] = message.errors.full_messages.to_sentence
      redirect_to :back
    end
  end

  def destroy_message
    authorize EmailMessage, :show?
    @message.destroy
    remote_redirect_to providers_path
  end

  def prev_message
    authorize EmailMessage, :show?
    old_message = @message
    @message = current_user.inbox.where(:created_at.lt => @message.created_at).order_by(:created_at).last
    @message = current_user.inbox.last if @message == nil || old_message == @message
    render partial: 'message_open_form'
  end

  def next_message
    authorize EmailMessage, :show?
    old_message = @message
    @message = current_user.inbox.where(:created_at.gt => @message.created_at).order_by(:created_at).first
    @message = current_user.inbox.first if @message == nil || old_message == @message
    render partial: 'message_open_form'
  end

  def first_message
    authorize EmailMessage, :show?
    @message = current_user.provider.email_messages.order_by(:created_at).first
    case params[:type]
      when 'open'
        render partial: 'message_open_form'
      when 'reply'
        render partial: 'message_reply_form'
      else
        render nothing: true
    end
  end

  def edit
    authorize Provider, :provider?
    @provider = current_user.provider.find(params[:id])
  end

  def create
    authorize Provider, :provider?
    @provider = current_user.provider.build(provider_params)
    @provider.user_id = current_user.id

    respond_to do |format|
      if @provider.save
        format.html { redirect_to providers_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize Provider, :provider?
    user = current_user
    if user.update(user_params)
      provider = current_user.provider
      if provider.update(provider_params)
        flash[:notice] = 'Your profile updated successfully'
      else
        flash[:error] = provider.errors.full_messages.to_sentence
      end
    else
      flash[:error] = user.errors.full_messages.to_sentence
    end
    redirect_to :back
  end

  def destroy
    authorize Provider, :provider?
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def lock
    authorize Provider, :provider?
    current_user.update(locked: true)
    render nothing: true
  end

  def unlock
    authorize Provider, :provider?
    if current_user.valid_password? params[:password]
      current_user.update(locked: false)
      render json: { status: 'Ok' }
    else
      render json: { status: 'Fail', error: 'Wrong password' }
    end
  end

  private

  def set_provider
    @provider = Provider.find(params[:id])
    unless @provider = current_user.provider.where(id: params[:id]).first
      flash[:alert] = 'Provider not found.'
      redirect_to root_url
    end
  end

  def check_lock
    redirect_to providers_path if current_user.locked
  end

  def find_message
    @message = EmailMessage.find(params[:message_id])
  end

  def prepare_params
    params[:provider][:expiration_date] = params[:provider][:expiration_date].to_time
  end

  def user_params
    params.require(:provider).require(:user).permit(
      :email
    )
  end

  def provider_params
    params.require(:provider).permit(
      :title,
      :first_name,
      :middle_name,
      :last_name,
      :degree,
      :speciality,
      :secondary_speciality,
      :dental_licence,
      :street_address,
      :suit_apt_number,
      :city,
      :state,
      :zip,
      :practice_street_address,
      :practice_suit_apt_number,
      :practice_city,
      :practice_state,
      :practice_zip,
      :expiration_date,
      :ein_tin,
      :npi,
      :dea,
      :upin,
      :nadean,
      :status,
      :accepting_patient,
      :enable_online_booking,
      :biography,
      :primary_phone,
      :mobile_phone,
      :alt_email,
      :username,
      :profile_image
      )
  end

  def message_params
    params.require(:email_message).permit(
        :subject_id,
        :body,
        :urgent,
        :attachment,
        :remote_attachment_url,
    )
  end

  def check_role
    redirect_to '/404' if current_user.blank? || current_user.role != :Provider
  end
end

development/app/helpers/providers_helper.rb
module ProvidersHelper
  def appointment_header_fields
    [
        { name: 'Time',      field: 'appointment_datetime_time' },
        { name: 'Patient',   field: 'patient' },
        { name: 'Provider',  field: 'provider' },
        { name: 'Appt Type', field: 'appointment_type' }
    ]
  end

  def my_todos_header_fields
    [
        { name: 'Type',    field: 'appointment_type' },
        { name: 'Patient', field: 'patient' },
        { name: 'Date',    field: 'created_at' }
    ]
  end
end

development/app/views/providers/_form_show_myaccount.html.slim
.modal-dialog
  .modal-content
    .modal-header
      p.title Edit User
    = flash[:error]
    = simple_form_for current_user.provider do |p|
      = hidden_field_tag :authenticity_token, form_authenticity_token
      .modal-body
        .scrollable-container
          .content
            .row-container.main-info
              .row
                .col-lg-2
                  .avatar
                    .attachment-container
                      - if gravatar?(current_user)
                        = gravatar_for(current_user, { class: 'avatar-image', alt: 'avatar' })
                      - else
                        - if current_user.provider.profile_image.present?
                          a.button-attachment href="#"
                            img src="#{current_user.provider.profile_image.url}" class='avatar-image' alt='avatar'
                        - else
                          .avatar-hint
                            p.review-text File must be: JPG, PNG, GIF
                            p.maxsize-text Max Size: 1MB
                            p.minres-text Min. Res: 300x300 px.
                            a.button.button-attachment
                              | Upload Photo
                        = p.file_field :profile_image
                .col-lg-10
                  .row
                    .col-lg-4
                      .form-group
                        = p.input :first_name, label: false, input_html: { class: 'form-control', placeholder: 'First Name' }
                    .col-lg-2
                      .form-group
                        = p.input :middle_name, label: false, input_html: { class: 'form-control', placeholder: 'M.I.' }
                    .col-lg-4
                      .form-group
                        = p.input :last_name, label: false, input_html: { class: 'form-control', placeholder: 'Last Name' }
                    .col-lg-2
                      .form-group
                        = p.input :title, as: 'select', collection: Provider.titles.map {|title| [title.to_s.titleize,title]}, selected: current_user.provider.title, input_html: { 'data-placeholder' => 'Title', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '1x', 'data-font' => '1x', class: 'select2' }
                  .row
                    .col-lg-2
                      .form-group
                        = p.input :degree, as: 'select', collection: Provider.degrees.map {|degree| ["#{degree.to_s.titleize == 'N/A Degree' ? 'N/A' : degree.to_s.titleize.upcase}",degree]}, selected: current_user.provider.degree, input_html: { 'data-placeholder' => 'Degree', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '1x', 'data-font' => '1x', class: 'select2' }
                    .col-lg-5
                      .form-group
                        = p.input :speciality, as: 'select', collection: Provider.specialities.map {|speciality| ["#{speciality.to_s.titleize == 'N/A Speciality' ? 'N/A' : speciality.to_s.titleize}",speciality]}, selected: current_user.provider.speciality, input_html: { 'data-placeholder' => 'Speciality', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '3x', 'data-font' => '1x', class: 'select2' }
                    .col-lg-5
                      .form-group
                        = p.input :secondary_speciality, label: false, input_html: { class: 'form-control', placeholder: 'Secondary speciality' }
              .row
                .col-lg-3
                  .form-group
                    = p.input :dental_licence, label: false, input_html: { class: 'form-control', placeholder: 'Dental Licence #' }
                .col-lg-6
                  .row
                    .col-lg-3
                      .form-group
                        = p.input :state, as: 'select', collection: State.all.map {|state| [state.abbr, state.name]}, selected: current_user.provider.state, input_html: { 'data-placeholder' => 'State', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '1x', 'data-font' => '1x', class: 'select2' }
                    .col-lg-9
                      .form-group
                        .input-group-custom
                          = p.text_field :expiration_date, class: 'form-control date-picker', placeholder: 'Expiration Date'
                          span.input-group-addon.input-group-addon-right.input-group-addon-calendar
                .col-lg-3
                  .form-group
                    = p.input :ein_tin, label: false, input_html: { class: 'form-control', placeholder: 'EIN/TIN' }
              .row
                .col-lg-3
                  .form-group
                    = p.input :npi, label: false, input_html: { class: 'form-control', placeholder: 'NPI' }
                .col-lg-3
                  .form-group
                    = p.input :dea, label: false, input_html: { class: 'form-control', placeholder: 'DEA' }
                .col-lg-3
                  .form-group
                    = p.input :upin, label: false, input_html: { class: 'form-control', placeholder: 'UPIN' }
              .row
                .col-lg-3
                  .form-group
                    = p.input :nadean, label: false, input_html: { class: 'form-control', placeholder: 'NADEAN' }
            .row-container.online-profile-and-booking
              .category-header
                p.title Online Profile and Appointment Booking
              .online-profile-content
                .row
                  .col-lg-4
                    .form-group
                      = p.input :status, as: 'select', collection: [['Active', true], ['Inactive', false]], selected: current_user.provider.status, input_html: { 'data-placeholder' => 'Status', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '3x', 'data-font' => '1x', class: 'select2' }
                    .form-group
                      .checkbox-custom
                        = p.check_box :accepting_patient, label: false, id: 'accepting-new-patients'
                        label[for="accepting-new-patients"]
                          span.checkbox-icon-container
                            span.checkbox-icon
                          span.checkbox-label Accepting new patients
                    .form-group
                      .checkbox-custom
                        = p.check_box :enable_online_booking, label: false, id: 'enable-online-booking'
                        label[for="enable-online-booking"]
                          span.checkbox-icon-container
                            span.checkbox-icon
                          span.checkbox-label Enable online Appt Booking
                  .col-lg-8
                    .form-group
                      = p.input :biography, as: 'text', label: false, input_html: { class: 'form-control', rows: 6, placeholder: 'Biography' }
            .row-container.practice-location
              .bordered-container
                .category-header
                  .row
                    .col-lg-10
                      p.title Practice Location and Provider Schedule
                    .col-lg-2
                      = link_to form_locations_path(opened_from_practice: true), class: 'button-small button-modal-open', id: 'myaccount-add-practice-location', 'data-target' => '#modal-settings-add-edit-location-practice', remote: true
                        i.fa.fa-plus
                .practice-location-content
                  .table-responsive
                    table.table
                      thead
                        tr
                          th
                            p Location Name
                          th
                            p City, State
                          th
                            p Provider Schedule
                          th
                            p Primary Location?
                      tbody
                        - current_user.provider.all_practice_locations.each do |location|
                          tr
                            td
                              p
                                = "#{location.location_name}, #{location.location_address}"
                            td
                              p
                                = "#{location.city}, #{location.state}"
                            td
                              - location.time_ranges_with_days.each do |range|
                                p
                                  = range
                            td
                              .checkbox-custom
                                = check_box_tag "location_#{location.id}", '', location.id == current_user.provider.practice_location.try(:id), class: 'checkbox primary_location', data: { id: location.id }
                                label[for="location_#{location.id}"]
                                  span.checkbox-icon-container
                                    span.checkbox-icon
            .row-container.userlogin-info
              .bordered-container
                .category-header
                  p.title User Login Info
                .userlogin-info-content
                  .row.first-row
                    .col-lg-7
                      .row
                        .col-lg-6
                          .form-group
                            = p.input :username, label: false, input_html: { class: 'form-control', placeholder: 'Username' }
                        .col-lg-6
                          .form-group
                            = p.input :practice_role, as: 'select', collection: Provider.practice_roles.to_a, selected: current_user.provider.practice_role, input_html: { 'data-placeholder' => 'Speciality', 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '3x', 'data-font' => '1x', class: 'select2' }
                    .col-lg-5
                      .form-group
                        .checkbox-custom.disabled
                          = p.check_box :status, label: false, readonly: 'readonly', disabled: 'disabled', id: 'user_active'
                          label[for="user_active"]
                            span.checkbox-icon-container
                              span.checkbox-icon
                            span.checkbox-label Active
                      .form-group
                        = link_to 'Reset Password', edit_user_registration_path, class: 'button'
                  .row.second-row
                    .col-lg-7
                      .row
                        .col-lg-6
                          = p.simple_fields_for :user, current_user do |u|
                            = u.input :id, as: 'hidden', value: current_user.id
                            .form-group
                              = u.input :email, label: false, input_html: { class: 'form-control input-email', placeholder: 'Personal Email' }
                        .col-lg-6
                          .form-group
                            = p.input :primary_phone, label: false, input_html: { class: 'form-control input-phone', placeholder: 'Personal Phone' }
                    - if !current_user.provider.emergency_access?
                      .col-lg-5
                        .form-group.pull-right
                          = link_to 'Request Emergency Access', request_emergency_access_providers_path, class: 'button button-danger button-modal-open', 'data-target': '#modal-request-emergency-access', remote: true
      .modal-footer
        = p.submit 'Save Changes', class: 'button'
        a.button.button-cancel data-target="#modal-myaccount" data-dismiss="modal" Cancel

development/app/views/providers/_navigation_provider.html.slim
nav.navbar-provider.navbar
  .navbar-header
      button.navbar-toggle.collapsed type="navbar-toggle button" data-toggle="collapse" data-target="#navbar-provider-main"
        span.fa.fa-bars.fa-2x
  #navbar-provider-main.collapse.navbar-collapse
    .left-block
      ul.main-menu.nav.navbar-nav
        li
          = link_to 'Dashboard', providers_path, class: 'item-dashboard'
        li
          = link_to 'Schedule', schedule_calendars_path, class: 'item-schedule'
        li
          = link_to 'Patients', patient_treatments_path, class: 'item-patients'
        li
          = link_to 'Messages', email_messages_path, class: 'item-messages'
        li
          a.item-erx href="#" eRx
        li
          a.item-labsimaging href="#" Labs/Imaging
        li
          a.item-reports href="#" Reports
        li
          a.item-billing href="#" Billing
        - if policy(:setting).show? || policy(:setting).schedule?
          li
            = link_to 'Settings', settings_practice_path, class: 'item-settings'
  ul.profile-menu.nav.navbar-nav.navbar-right class=(current_user.provider.emergency_access? ? 'navbar-emergency-access' : '')
    li
      .dropdown
        a.profile-user.dropdown-toggle data-toggle="dropdown"
          span.name
            - if current_user.present?
              span = current_user.provider.title
              | .
              '
              span = current_user.provider.last_name
          - if gravatar?(current_user)
            = gravatar_for(current_user, { class: 'avatar', alt: 'avatar' })
          - else
            - if current_user.provider.profile_image.present?
              img src="#{current_user.provider.profile_image.url}" class='avatar' alt='avatar'
            - else
              = image_tag 'avatar-empty.svg', size: "100", class: "avatar avatar-empty"
          i.arrow.fa.fa-angle-down
        ul.dropdown-menu
          - if current_user.provider.emergency_access
            li
              = link_to 'Disable Emergency Access', set_emergency_access_providers_path(id: current_user.provider.id, emergency_access: false)
          li
            = link_to 'My Account', show_myaccount_providers_path, remote: true
          li
            a href="#" data-toggle="modal" data-target="#modal-about-ehr1" About EHR1
          - if current_user.authy_id.present? && current_user.authy_enabled
            li
              = link_to 'Disable 2FA', user_disable_authy_path(id: current_user.id), method: :post
          - else
            li
              = link_to 'Enable 2FA', user_enable_authy_path
          li
            = link_to 'Log out', destroy_user_session_path, method: 'delete'
#modal-about-ehr1.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        a.close-button href="#" data-target="#modal-about-ehr1" data-dismiss="modal"
      .modal-body
        .top-block
          p EHR1 - Electronic Health Record Version 1.0
          p Copyright © 2015 EHR1. All Rights Reserved
        .center-block
          .logo
        .bottom-block
          p
            | View the&nbsp;
            a href="#" Healthcare Provider User Agreement
            | ,&nbsp;
            a href="#" Privacy policy
            |  and&nbsp;
            a href="#" Terms of Use
            | .
#modal-lockscreen.modal.fade data-keyboard="false" data-backdrop=""
  .modal-dialog
    .modal-content
      .modal-header
        .logo
      .modal-body
        .lockscreen-icon
        .form-group
          input.form-control type="password" id="lockscreen_password" placeholder="Password"
      .modal-footer
        .form-group
          = link_to 'Unlock', '#', class: 'button', id: 'unlock'
#modal-myaccount.modal.fade
#modal-request-emergency-access.modal.fade

development/app/views/providers/show.html.slim
p#notice = notice

p
  strong User:
  = @provider.user

= link_to 'Edit', edit_provider_path(@provider)
'|
= link_to 'Back', providers_path