development/config/routes.rb
Rails.application.routes.draw do

  # Only for ENV=development
  # mount Logster::Web => "/logs"

  resources :providers do
    collection do
      get :schedule
      get :add_patient
      get :show_myaccount
      get :request_emergency_access
      patch :update_emergency_access
      get :set_emergency_access
      get :set_status
      get :invite_to_portal
      get :download_pdf
      get :send_invite_email
      get :add_patient_from_appointment
      post :save_message
      get :destroy_message
      get :prev_message
      get :next_message
      get :first_message
      get :patients
      get :lock
      post :unlock
    end
  end

  resources :patients,     only: [:index, :create, :update] do
    collection do
      post :simple_create
      get  :appointments_show
      get  :appointments_status_actions
      get  :new_appointment
      get  :provider_full_info
      get  :myprofile
      patch :update_myprofile
      get  :myhealth
      post :create_emergency_contact
    end
  end

  resources :appointments, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get :referrals
      get :patients
      get :patient_full_info
      get :reschedule
    end
  end

  resources :block_outs, only: [:create]

  resources :referrals,  only: [:new, :create]

  resources :patient_appointments, only: [:create]

  resources :practices, only: [:new, :create, :edit, :update]

  resources :locations, only: [:create, :update] do
    collection do
      get :form
      get :primary_location
    end
  end

  resources :immunizations, except: [:destroy, :show] do
    collection do
      get  :name_block
      post :vaccines
    end
  end

  namespace :settings do
    get   :practice
    get   :access_permissions
    patch :update_permissions
    get   :set_admin
    get   :schedule
    patch :update_schedule
    get   :add_user_added_practice
    get   :set_practice_location_color
    get   :get_schedule_fields
    get   :update_schedule_fields
    get   :update_schedule_color_fields
    get   :add_schedule_fields
    get   :destroy_schedule_fields
  end

  resources :patient_treatments, only: [:index] do
    collection do
      get  :search_patients
      get  :active_patients
      get  :show_patient_main
      get  :tooth_activity
      get  :show_patient_diagnoses
      get  :diagnosis_codes
      get  :show_patient_medications
      get  :add_patient_diagnoses
      post :create_diagnosis
      patch :update_diagnosis
      get  :add_patient_medications
      post :create_medication
      patch :update_medication
      get  :portions
      get  :medications
      get  :show_patient_allergy
      post :create_allergy
      patch :update_allergy
      get  :edit_patient_smoking
      post :update_smoking_status
      get  :add_patient_medical_history
      patch :update_medical_history
      get  :add_patient_advanced_directives
      patch :update_advanced_directive
      get  :add_patient_insurance
      get  :add_patient_payer
      get  :show_patient_full_perio
      patch :update_full_perio
      get  :show_patient_perio_data_entry
      patch :update_tooth
      get  :set_tooth_bsp
      get  :add_patient_encounter
      post :create_patient_encounter
      patch :update_encounter
      get  :providers
      get  :procedures
      get  :procedure_codes
      get  :encounters
      get  :add_patient_procedure
      get  :show_patient_procedure
      post :create_procedure
      patch :update_procedure
      get  :encounter_full_info
      patch :update_guarantor
      post :create_payer
      post :create_insurance
      get :payers
      get :guarantor
    end
  end

  resources :representatives do
    collection do
      post :activate
    end
    member do
      post :reset_password
    end
  end

  resources :email_messages, only: [:index, :new, :create] do
    collection do
      get  :add_subject
      get :get_subjects
      get :update_subject
      get :remove_subject
      post :create_main
      post :create_to_practice
      post :create_from_patient_to_practice
      post :create_reply
      get  :patients
      get  :practices
      get  :patient_practices
      get :open_message
      get :new_message_to_patient
      get :forward_message_from_patient
      get :new_message_in_practice
      get :new_message_to_practice
      get :reply_to_message_in_practice_contacts
      get :forward_message_in_practice_contacts
      get :contacts
      get :contacts_pagination
      get :contacts_practices
      get :find_practices
      get :add_contact
      get :new_contact
      get :message
      get :new_tab
      get :to_archive
      get :delete_message
      get :search_message
      get :favorite_contact
      get :mark_as_read
    end
  end

  get 'landings/index'
  get 'admin/index'

  post 'text', to: 'text_messages#create'

  root to: 'landings#index'

  devise_for :users,
    path_names: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-two-factor',
      verify_authy_installation: '/verify-installation'
    },
    controllers: {
      confirmations: 'confirmations',
      passwords:     'passwords',
      registrations: 'registration',
      sessions:      'sessions',
      devise_authy:  'authy'
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :calendars do
    collection do
      get :schedule
      get :open_reschedule
      patch :reschedule
      get :get_calendars
      get :filter
      get :new_appointment
      get :targets
    end
    member do
      post :move
      post :resize
    end
  end

  resources :tables, except: [:show] do
    collection do
      get :records
    end
  end

  namespace :sorter do
    get :appointments
    get :messages
    get :todos
  end

  namespace :dashboard do
    get :index
  end

  namespace :practice_sessions do
    get :sign_in
  end

  namespace :zipcode do
    post :city_set
    post :state_set
    post :zip_set
  end

  namespace :web_console do
    get :show_web_console_alert
  end

  match 'admin',    to: 'admin#index',  via: [:get]
  match 'explorer', to: 'tables#index', via: [:get]

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

development/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  layout 'patient'

  before_filter :check_role_patient,  only: [:index, :appointments_show, :appointments_status_actions, :new_appointment,
                                             :myhealth, :myprofile, :update_myprofile]
  before_filter :check_role_provider, only: [:create, :simple_create]
  before_filter :check_role,          only: [:update, :provider_full_info, :create_emergency_contact]

  before_filter :prepare_params, only: [:create, :simple_create]

  def index
    @message = current_user.inbox.order_by(:created_at).first
    @appointments = current_user.patient.appointments.where(:appointment_datetime.ge => Time.now.beginning_of_day)
                                                     .order_by(:appointment_datetime)
    @appointment = current_user.patient.appointments.order_by(:appointment_datetime).last
    @events_count = 1 + (@message.present? ? 1 : 0) + (@appointment.present? ? 1 : 0)
    render layout: "patient"
  end

  def create
    user = User.create(user_params)
    if user.persisted?
      patient = Patient.create(patient_params.merge({provider_id: current_user.provider.main_provider_id, user_id: user.id, code: Activation.code}))
      if patient.persisted?
        redirect_to invite_to_portal_providers_path(patient_id: patient.id)
      else
        flash[:error] = patient.errors.full_messages.to_sentence
        redirect_to add_patient_providers_path
      end
    else
      flash[:error] = user.errors.full_messages.to_sentence
      redirect_to add_patient_providers_path
    end
  end

  def simple_create
    user = User.create(user_params)
    if user.persisted?
      patient = Patient.create(patient_params.merge({provider_id: current_user.provider.main_provider_id, user_id: user.id, code: Activation.code}))
      if patient.persisted?
        redirect_to new_appointment_path
      else
        flash[:error] = patient.errors.full_messages.to_sentence
        redirect_to add_patient_from_appointment_providers_path
      end
    else
      flash[:error] = user.errors.full_messages.to_sentence
      redirect_to add_patient_from_appointment_providers_path
    end
  end

  def update
    params[:user][:patient][:birth] = params[:user][:patient][:birth].to_time
    params[:user][:patient][:zip]   = params[:user][:patient][:zip].to_i
    user = Patient.find(params[:id]).user
    if user.update(user_params)
      patient = user.patient
      if patient.update(patient_params)
        emergency_contact = patient.emergency_contacts.first
        if emergency_contact.update(emergency_contact_params(params[:user][:patient]))
          next_kin = patient.next_kin
          if next_kin.update(next_kin_params)
            flash[:notice] = 'Patient updated successfully'
            remote_redirect_to(patient_treatments_path)
          else
            flash[:error] = next_kin.errors.full_messages.to_sentence
            redirect_to show_patient_main_patient_treatments_path(id: params[:id])
          end
        else
          flash[:error] = emergency_contact.errors.full_messages.to_sentence
          redirect_to show_patient_main_patient_treatments_path(id: params[:id])
        end
      else
        flash[:error] = patient.errors.full_messages.to_sentence
        redirect_to show_patient_main_patient_treatments_path(id: params[:id])
      end
    else
      flash[:error] = user.errors.full_messages.to_sentence
      redirect_to show_patient_main_patient_treatments_path(id: params[:id])
    end
  end

  def appointments_show
    @appointments_upcoming = current_user.patient.appointments.where(:appointment_datetime.ge => Time.now).order_by(:appointment_datetime)
    @appointments_past = current_user.patient.appointments.where(:appointment_datetime.lt => Time.now).order_by(:appointment_datetime)
  end

  def appointments_status_actions
    if params[:status].present?
      status_id = params[:status].to_i
      Appointment.find(params[:id])
                 .update(status: status_id, appointment_status_id: status_id)     if params[:id].present?
      Appointment.where(:id.in => JSON.parse(params[:ids]))
                 .update_all(status: status_id, appointment_status_id: status_id) if params[:ids].present?
    end
    @appointments_upcoming = current_user.patient.appointments.where(:appointment_datetime.ge => Time.now).order_by(:appointment_datetime)
    render partial: 'patients/appointments_upcoming', locals: { appointments_upcoming: @appointments_upcoming }, layout: nil
  end

  def new_appointment
    @providers = Provider.all.map{ |provider| ["#{provider.title} #{provider.last_name} #{provider.first_name}", provider.id] }
  end

  def myhealth
    @medications = Medication.where(:id.in => current_user.patient.diagnoses.map(&:id))
  end

  def myprofile
  end

  def update_myprofile
    params[:user][:patient][:birth] = params[:user][:patient][:birth].to_time
    params[:user][:patient][:zip]   = params[:user][:patient][:zip].to_i
    user = Patient.find(params[:id]).user
    if user.update(user_params)
      patient = user.patient
      if patient.update(patient_params)
        flash[:notice] = 'Patient updated successfully'
      else
        flash[:error] = patient.errors.full_messages.to_sentence
      end
    else
      flash[:error] = user.errors.full_messages.to_sentence
    end
    redirect_to :back
  end

  def provider_full_info
    render json: Provider.find(params[:provider_id]).all_locations.to_json
  end

  def create_emergency_contact
    if emergency_contact = EmergencyContact.create(emergency_contact_params(params))
      flash[:notice] = 'Emergency contact successfully'
    else
      flash[:error] = emergency_contact.errors.full_messages.to_sentence
    end
    redirect_to :back
  end

  private

  def prepare_params
    params[:user][:patient][:birth] = params[:user][:patient][:birth].to_time
    params[:user].merge!({email: "#{Activation.code}@mail.com"}) unless params[:user][:email].present?
    params[:user].merge!({password: @code,
                          password_confirmation: @code,
                          confirmed_at: Time.now,
                          role: :Patient})
  end

  def user_params
    params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :confirmed_at,
        :role
    )
  end

  def patient_params
    params.require(:user).require(:patient).permit(
        :provider_id,
        :first_name,
        :last_name,
        :middle_name,
        :birth,
        :gender,
        :social_number,
        :patient_id,
        :active,
        :declined_portal_access,
        :preferred_language,
        :ethnicity,
        :american_race,
        :asian_race,
        :african_race,
        :hawaiian_race,
        :white_race,
        :undetermined_race,
        :email_reminder,
        :sms_reminder,
        :immunization_registry,
        :mobile_phone,
        :primary_phone,
        :work_phone,
        :ext,
        :street_address,
        :city,
        :state,
        :zip,
        :profile_image
    )
  end

  def emergency_contact_params(parameters)
    parameters.require(:emergency_contact).permit(
        :first_name,
        :last_name,
        :middle_name,
        :relation,
        :mobile_phone,
        :email,
        :street_address,
        :city,
        :state,
        :zip
    )
  end

  def next_kin_params
    params.require(:user).require(:patient).require(:next_kin).permit(
        :first_name,
        :last_name,
        :middle_name,
        :relation,
        :mobile_phone,
        :email,
        :street_address,
        :city,
        :state,
        :zip
    )
  end

  def check_role_patient
    authorize Patient, :patient?
  end

  def check_role_provider
    authorize Patient, :create?
  end

  def check_role
    if current_user.role == :Provider
      authorize Patient, :update?
    elsif current_user.patient?
      authorize Patient, :patient?
    else
      redirect_to '/404'
    end
  end
end

development/app/views/patients/_navigation_patient.html.slim
nav.navbar-patient.navbar
  .navbar-header
      button.navbar-toggle.collapsed type="navbar-toggle button" data-toggle="collapse" data-target="#navbar-patient-main"
        span.fa.fa-bars.fa-2x
  #navbar-patient-main.collapse.navbar-collapse
    .left-block
      ul.main-menu.nav.navbar-nav
        li
          = link_to 'Dashboard', patients_path, class: 'item-dashboard'
        li
          = link_to 'Appointments', appointments_show_patients_path, class: 'item-appointments'
        li
          = link_to 'Messages', email_messages_path  , class: 'item-messages'
        li
          = link_to 'My Health', myhealth_patients_path, class: 'item-myhealth'
        li
          = link_to 'My Profile', myprofile_patients_path, class: 'item-myprofile'
        li
          a.item-mydocuments href="#" My Documents
  ul.profile-menu.nav.navbar-nav.navbar-right
    li
      .dropdown
        a.profile-user.dropdown-toggle data-toggle="dropdown"
          span.name
            - if current_user.present?
              span = current_user.patient.last_name
          - if gravatar?(current_user)
            = gravatar_for(current_user, { class: 'avatar', alt: 'avatar' })
          - else
            - if current_user.patient.profile_image.present?
              img src="#{current_user.patient.profile_image.url}" class='avatar' alt='avatar'
            - else
              = image_tag 'avatar-empty.svg', size: "100", class: "avatar avatar-empty"
          i.arrow.fa.fa-angle-down
        ul.dropdown-menu
          li
            = link_to 'My Profile', myprofile_patients_path, class: 'item-myprofile'
          li
            = link_to 'My Health', myhealth_patients_path, class: 'item-myhealth'
          li
            a href="#" Account
          li
            = link_to 'Log out', destroy_user_session_path, method: 'delete'
#modal-make-an-appt.modal.modal.fade

development/app/views/patients/appointments_show.html.slim
#appointments-wrapper.container.content
  .top-block
    h4.h4-title
      | Welcome  
      - if  current_user.present?
        span.authorization-welcome-username
          = current_user.patient.last_name
    .row
      .col-lg-12
        h4 
          | Today/
          = Time.now.strftime("%B %d, %Y")
    .row
      .tabs
        ul.nav.nav-tabs
          li.active
            a href="#tab-appointments-upcoming" data-toggle="tab" Upcoming Appts
          li
            a href="#tab-appointments-past" data-toggle="tab" id="tab-appts-past-toggle" Past Appts
        .row
          .col-lg-12
            .buttons
              .btn-group
                = link_to 'Make an Appt', new_appointment_patients_path, remote: true, class: 'button button-medium'
              .btn-group
                select.select2#actions-menu data-placeholder="Action" data-theme="green-dark" data-arrow="2x" data-padding="3x" data-font="2x" data-width="146px"
                  option value=""
                  option value="0" Confirm
                  option value="1" Reschedule
                  option value="2" Cancel
  .content-block
    .tab-content
      #tab-appointments-upcoming.tab-pane.active.fade.in
        .panel.panel-default
          .table-responsive
            table.table.table-grayed.table-grayed-checkboxed#appointments-upcoming
              = render 'appointments_upcoming'
      #tab-appointments-past.tab-pane.fade
        .panel.panel-default
          .table-responsive
            table.table.table-grayed
              thead
                tr
                  th
                    p Date
                  th
                    p Time
                  th
                    p ApptType
                  th
                    p Prov
                  th
                    p Status
              tbody
                - if !@appointments_past.any?
                  tr
                    td colspan="5"
                      p.table-empty You doesn't have any past appointments.
                - @appointments_past.each do |appointment|
                  tr
                    td
                      p
                        = appointment.try(:appointment_datetime).try(:strftime, '%m/%d/%Y')
                    td
                      p
                        = local_time(appointment.appointment_datetime, '%l:%M %p')
                    td
                      p
                        = appointment.appointment_type.try(:appt_type)
                    td
                      p
                        = "#{appointment.try(:patient).try(:provider).try(:title)}. #{appointment.try(:patient).try(:provider).try(:first_name)} #{appointment.try(:patient).try(:provider).try(:last_name)}"
                    td
                      p
                        = appointment.appointment_status.try(:name)
/ #actions-no-appt-selected-modal.modal.fade
/   .modal-dialog.modal-lg
/     .modal-header
/       button.modal-close.close type="button" data-dismiss="modal" &times;
/       h4 No Appt Selected
#modal-make-an-appt.modal.fade
javascript:
  $('.item-appointments').parent().addClass('active');

development/app/views/patients/index.html.slim
#dashboard-wrapper.content.container
  h4.h4-title
    | Welcome
    - if current_user.present?
      span.authorization-welcome-username = current_user.patient.last_name
  .row
    .col-lg-9.left-block
      - if @appointments.any?
        .form-row-field
          div
            h4
              | Upcoming appointments
              span.appointments-count
              | (#{@appointments.count})
        .panel.panel-default
          - @appointments.each do |appointment|
            .panel-body
              .row
                .col-lg-2.col-md-2.col-sm-3
                  p
                    = appointment.try(:appointment_datetime).try(:strftime, '%b %d')
                  p.secondary-text
                    - differ = Time.now.day - appointment.try(:created_at).try(:day).to_i
                    = differ == 0 ? "Today" : "#{differ} days ago"
                .col-lg-8.col-md-8.col-sm-6.col-xs-9
                  p
                    = appointment.try(:reason)
                  p.secondary-text
                    = "Provider : #{appointment.try(:patient).try(:provider).try(:to_label)}"
                .col-lg-2.col-md-2.col-sm-3.col-xs-3
                  = link_to 'View', appointment_path(appointment), remote: true, class: "button pull-right"
      .form-row-field
        div
          h4.h4-title
            | Notification
            span.notifications-count
              = "(#{@events_count})"
      .panel.panel-default
        .panel-body
          .row
            .col-lg-1.col-sm-1.col-md-1.col-xs-2
              .notification-icon-container
                img.notification-icon src = image_path('icon_notificationtable-dark.svg') /
            .col-lg-9.col-sm-7.col-md-9.col-xs-8
              p Aug 30 ( 1h ago )
              p.secondary-text Lab Tests Result(s) Available
            .col-lg-2.col-sm-4.col-md-2.col-xs-2
              a.btn-remove-notification.pull-right href="#"
                img src = image_path('icon_notification-remove.svg') /
        - if @message.present?
          .panel-body
            .row
              .col-lg-1.col-sm-1.col-md-1.col-xs-2
                .notification-icon-container
                  img.notification-icon src = image_path('icon_message-dark.svg') /
              .col-lg-9.col-sm-7.col-md-9.col-xs-8
                p
                  = @message.created_at.strftime('%b %d ( [hours]h ago )')
                p.secondary-text
                  = "New Message - #{@message.subject.try(:name)}, From: #{@message.from.person.full_name}"
              .col-lg-2.col-sm-4.col-md-2.col-xs-2
                a.btn-remove-notification.pull-right href="#"
                  img src = image_path('icon_notification-remove.svg') /
        - if @appointment.present?
          .panel-body
            .row
              .col-lg-1.col-sm-1.col-md-1.col-xs-2
                .notification-icon-container
                  img.icon-invert-color.notification-icon src = image_path('nav-patient-appointments.svg') /
              .col-lg-9.col-sm-7.col-md-9.col-xs-8
                p
                  = @appointment.appointment_datetime.strftime('%b %d ( [hours]h ago )')
                p.secondary-text
                  = @appointment.appointment_type.appt_type
              .col-lg-2.col-sm-4.col-md-2.col-xs-2
                a.btn-remove-notification.pull-right href="#"
                  img src = image_path('icon_notification-remove.svg') /
    .col-lg-3.right-block
      .form-row-field
        div
          h4 Quick Links
      .panel.panel-default
        .panel-body
          ul
            li
              = link_to new_appointment_patients_path, remote: true, class: 'secondary-text-dark'
                i.fa.fa-angle-right
                p Make an Appt
            li
              = link_to new_message_to_practice_email_messages_path, remote: true, class: 'secondary-text-dark'
                i.fa.fa-angle-right
                p Send a Message
            li
              a.secondary-text-dark href="#"
                i.fa.fa-angle-right
                p View Clinical Summanes
            li
              a.secondary-text-dark href="#"
                i.fa.fa-angle-right
                p View Lab Results
#modal-make-an-appt.modal.fade
.messages-wrapper
  #modal-message-new.modal.fade
#modal-show-appointment-details.modal-provider.modal.fade
javascript:
  $('.item-dashboard').parent().addClass('active');

development/app/views/patients/myprofile.html.slim
#myprofile-wrapper.container.content
  = simple_form_for current_user, url: update_myprofile_patients_path(id: current_user.patient.id) do |u|
    = u.simple_fields_for :patient, current_user.patient do |p|
      .row.top-block
        .col-lg-12
          h4 Basic Info
          .panel.panel-default
            .panel-body
              .photo-container.pull-left
                a.button-attachment href="#"
                  - if gravatar?(current_user)
                    = gravatar_for(current_user, { class: 'photo-patient', alt: 'avatar' })
                  - else
                    - if current_user.patient.profile_image.present?
                      img src="#{current_user.patient.profile_image.url}" class='photo-patient' alt='avatar'
                    - else
                      = image_tag 'avatar-empty-white.svg', size: 500, class: "avatar avatar-empty avatar-empty-dark"
                = p.file_field  :profile_image
              .row.pull-right
                .col-lg-5
                  .form-group
                    = p.input :first_name, label: false, input_html: { class: 'form-control', placeholder: 'First Name' }
                .col-lg-2
                  .form-group
                    = p.input :middle_name, label: false, input_html: { class: 'form-control', placeholder: 'M.I.' }
                .col-lg-5
                  .form-group
                    = p.input :last_name, label: false, input_html: { class: 'form-control', placeholder: 'Last Name' }
              .row.pull-right
                .col-lg-5
                  .form-group
                    = p.input :birth, as: :date_picker, label: false, input_html: { class: 'form-control date-picker', placeholder: 'Date of Birth' }
                .col-lg-3
                  .form-group
                    = p.input :gender, as: :select, label: false, collection: Patient.genders.to_a, input_html: { 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '3x', 'data-font' => '1x', class: 'select2' }, include_blank: false
              .row.pull-right
                .col-lg-5
                  p Account Access
                  = link_to 'Request Password Reset Email', edit_user_registration_path, class: 'button disabled', tabindex: '-1'
      .row.bottom-block
        .col-lg-6.left-block
          h4 My Contact Infrormation
          .panel.panel-default
            .panel-body
              .form-group
                = p.input :mobile_phone, as: :tel, label: false, input_html: { class: 'form-control input-phone', placeholder: 'Cell Phone' }
              .form-group
                = u.input :email, as: :email, label: false, input_html: { class: 'form-control input-email', placeholder: 'Email' }
              .form-group
                = p.input :primary_phone, as: :tel, label: false, input_html: { class: 'form-control input-phone', placeholder: 'Home Phone' }
              .form-group
                = p.input :street_address, label: false, input_html: { class: 'form-control', placeholder: 'Address' }
              .row
                .col-lg-4
                  .form-group
                    = p.input :city, label: false, input_html: { class: 'form-control', placeholder: 'City' }
                .col-lg-4
                  .form-group
                    = p.input :state, as: :numeric, label: false, input_html: { class: 'form-control', placeholder: 'State' }
                .col-lg-4
                  .form-group
                    = p.input :zip, as: :numeric, label: false, input_html: { class: 'form-control', placeholder: 'Zip' }
              .form-group
                = p.input :work_phone, as: :tel, label: false, input_html: { class: 'form-control input-phone', placeholder: 'Work Phone' }
              .controls.pull-right
                /a.button Edit
                = u.submit 'Save', class: 'button'
        .col-lg-6.right-block
          h4 Emergency Contact
          .panel.panel-default
            = simple_form_for EmergencyContact.new, url: create_emergency_contact_patients_path do |ec|
              = ec.input :patient_id, as: :hidden, input_html: { value: current_user.patient.id }
              .panel-body
                .row
                  .col-lg-4
                    .form-group
                      = ec.input :first_name, label: false, input_html: { class: 'form-control', placeholder: 'First Name' }
                  .col-lg-4
                    .form-group
                      = ec.input :middle_name, label: false, input_html: { class: 'form-control', placeholder: 'M.I.' }
                  .col-lg-4
                    .form-group
                      = ec.input :last_name, label: false, input_html: { class: 'form-control', placeholder: 'Last Name' }
                .form-group
                  = ec.input :relation, as: :select, label: false, collection: EmergencyContact.relations.to_a, input_html: { 'data-theme' => 'gray-lighter', 'data-arrow' => '2x', 'data-padding' => '3x', 'data-font' => '1x', class: 'select2' }, include_blank: false
                .form-group
                  = ec.input :mobile_phone, as: :tel, label: false, input_html: { class: 'form-control', placeholder: 'Phone' }
                .form-group
                  = ec.input :email, as: :email, label: false, input_html: { class: 'form-control input-email', placeholder: 'Email' }
                .form-group
                  = ec.input :street_address, as: :text, label: false, input_html: { class: 'form-control', placeholder: 'Address', rows: 3 }
                .controls.pull-right
                  /a.button Edit
                  = ec.submit 'Save', class: 'button'
javascript:
  $('.item-myprofile').parent().addClass('active');

development/app/views/patients/new_appointment.js.erb
$("#modal-make-an-appt").html("<%= escape_javascript(render 'new_appointment_form') %>");
$("#modal-make-an-appt").modal("show");

initPickers();
initSelect2('#modal-make-an-appt');

var NewAppointmentController = function() {
  var modal = $('#modal-make-an-appt');
  var select = modal.find('#patient_appointment_provider_id');
  var location = modal.find('#patient_appointment_location');

  this.initialize = function() {
    SetSelectedProvider();
    select.change(function() {
      SetSelectedProvider();
    });
  };

  var SetSelectedProvider = function() {
    var provider_id = select.find(':selected').val();
    location.html('');
    $.ajax({
      url: '<%= Rails.application.routes.url_helpers.provider_full_info_patients_path %>',
      data: {
        provider_id: provider_id
      }
    }).done(function(locations) {
      locations.forEach(function(address) {
        var option = $('<option />').attr('value', address).text(address);
        location.append(option);
      });
    });
  };
};

$(function() {
  var newAppointmentController = new NewAppointmentController();
  newAppointmentController.initialize();
});